export type Book={id:string;title:string;author:string;year:string;genre:string;minutes:string;description:string;accent:string;sourceUrl:string};
export const books:Book[]=[
{id:"pride",title:"Pride and Prejudice",author:"Jane Austen",year:"1813",genre:"Romance",minutes:"12h 11m",accent:"#294239",sourceUrl:"https://www.gutenberg.org/ebooks/1342",description:"Wit, first impressions and the slow surprise of falling in love."},
{id:"alice",title:"Alice's Adventures in Wonderland",author:"Lewis Carroll",year:"1865",genre:"Fantasy",minutes:"3h 03m",accent:"#74abb0",sourceUrl:"https://www.gutenberg.org/ebooks/11",description:"A curious girl follows a white rabbit into a world where logic bends."},
{id:"sherlock",title:"The Adventures of Sherlock Holmes",author:"Arthur Conan Doyle",year:"1892",genre:"Mystery",minutes:"7h 34m",accent:"#25231f",sourceUrl:"https://www.gutenberg.org/ebooks/1661",description:"Twelve classic cases for the world's most famous consulting detective."},
{id:"frankenstein",title:"Frankenstein",author:"Mary Shelley",year:"1818",genre:"Gothic",minutes:"8h 35m",accent:"#152025",sourceUrl:"https://www.gutenberg.org/ebooks/84",description:"Ambition, creation and the terrible cost of abandoning responsibility."},
{id:"dracula",title:"Dracula",author:"Bram Stoker",year:"1897",genre:"Gothic",minutes:"15h 28m",accent:"#321621",sourceUrl:"https://www.gutenberg.org/ebooks/345",description:"Diaries, letters and newspaper clippings build a chilling mystery."},
{id:"time-machine",title:"The Time Machine",author:"H. G. Wells",year:"1895",genre:"Science Fiction",minutes:"3h 14m",accent:"#25415a",sourceUrl:"https://www.gutenberg.org/ebooks/35",description:"A daring journey through deep time reveals an unexpected human future."},
{id:"two-cities",title:"A Tale of Two Cities",author:"Charles Dickens",year:"1859",genre:"Classic",minutes:"13h 46m",accent:"#3b3e35",sourceUrl:"https://www.gutenberg.org/ebooks/98",description:"Paris and London become the stage for sacrifice, revolution and love."},
{id:"treasure",title:"Treasure Island",author:"Robert Louis Stevenson",year:"1883",genre:"Adventure",minutes:"6h 58m",accent:"#184548",sourceUrl:"https://www.gutenberg.org/ebooks/120",description:"A map, a ship, a hidden fortune and one unforgettable pirate."},
{id:"oz",title:"The Wonderful Wizard of Oz",author:"L. Frank Baum",year:"1900",genre:"Fantasy",minutes:"3h 53m",accent:"#4d7462",sourceUrl:"https://www.gutenberg.org/ebooks/55",description:"Dorothy takes the yellow brick road toward courage, friendship and home."},
{id:"secret-garden",title:"The Secret Garden",author:"Frances Hodgson Burnett",year:"1911",genre:"Children",minutes:"7h 15m",accent:"#5c704f",sourceUrl:"https://www.gutenberg.org/ebooks/113",description:"A hidden garden changes the lives of three lonely children."}
];